Release v42
flathub/org.gnome.Todo pull request #21
Opened 2022-07-27 09:51 UTC by ItsJamie9494

2022-07-27 09:51 UTC, ItsJamie9494 commented
bot, build

2022-07-27 13:10 UTC, GeorgesStavracas requested changes

2022-07-27 13:10 UTC, GeorgesStavracas commented on org.gnome.Todo.json
> +                    "url": "https://github.com/flatpak/libportal.git"
I don't recommend using libportal from the main branch - it is subject to API breaks

2022-07-27 13:10 UTC, GeorgesStavracas commented on org.gnome.Todo.json
> +                    "sha256": "8042de40207e682518e31ed7e35a0ad174eefed52c08b3047e3068a4bd261ea1"
For Flathub, it **is** preferred to keep using the tarballs for now for GNOME dependencies

2022-07-27 15:14 UTC, ItsJamie9494 commented on org.gnome.Todo.json
> +                    "url": "https://github.com/flatpak/libportal.git"
I know, I'd prefer not either, but either my brain at 4am was not working or libportal 0.6 wasn't

2022-07-27 15:17 UTC, ItsJamie9494 commented on org.gnome.Todo.json
> +                    "sha256": "8042de40207e682518e31ed7e35a0ad174eefed52c08b3047e3068a4bd261ea1"
I'm a little confused as you're requesting to change...the tarball URL?

2022-07-27 15:21 UTC, GeorgesStavracas commented on org.gnome.Todo.json
> +                    "sha256": "8042de40207e682518e31ed7e35a0ad174eefed52c08b3047e3068a4bd261ea1"
I don't know why i picked this line in particular, it was supposed to be one of the changes below this one :smile:

2022-07-27 20:29 UTC, A6GibKm commented on org.gnome.Todo.json
> +                    "url": "https://gitlab.gnome.org/GNOME/evolution-data-server.git"
Please a tarball from download.gnome.org, like https://download.gnome.org/sources/evolution-data-server/3.44/evolution-data-server-3.44.3.tar.xz unless there is something very specific you need from git.

Do note that using `branch` is extremely discouraged in Flathub, if you ping a commit it will break as soon as someone pushes anything to that branch and if you dont then the build is not reproducible.

2022-07-27 20:29 UTC, A6GibKm commented on org.gnome.Todo.json
> +                    "url": "https://github.com/flatpak/libportal.git"
Please consider using the tarball https://github.com/flatpak/libportal/releases/download/0.6/libportal-0.6.tar.xz. Ultimately a matter of preference though.

2022-07-27 20:29 UTC, A6GibKm commented on org.gnome.Todo.json
> +                "-Dvapi=false"
I think you can also `-Dintrospection=disabled`, no need to generate gir for bindings.

2022-07-27 20:30 UTC, ItsJamie9494 commented on org.gnome.Todo.json
> +                    "url": "https://gitlab.gnome.org/GNOME/evolution-data-server.git"
I do actually need this branch, when I used 3.45, it wasn't picking up GCR properly.

I'll check again though

2022-07-27 20:30 UTC, ItsJamie9494 commented on org.gnome.Todo.json
> +                    "url": "https://github.com/flatpak/libportal.git"
Thanks for letting me know where the tarball was :)

2022-07-27 20:32 UTC, A6GibKm commented on org.gnome.Todo.json
> +                    "url": "https://gitlab.gnome.org/GNOME/evolution-data-server.git"
Then use a specific commit from the branch and maybe document it in the commit.

2022-07-28 06:22 UTC, A6GibKm commented on org.gnome.Todo.json
> +                    "url": "https://gitlab.gnome.org/GNOME/evolution-data-server.git"
You have to remove the branch too.

2022-07-28 06:26 UTC, merged